services:
  matterbridge:
    container_name: matterbridge
    image: luligu/matterbridge:latest
    network_mode: host
    restart: always
    volumes:
      - /etc/matterbridge/Matterbridge:/root/Matterbridge
      - /etc/matterbridge/.matterbridge:/root/.matterbridge
      