services:
  immich-server:
    container_name: immich
    image: ghcr.io/immich-app/immich-server:latest
    volumes:
      - /home/admin/Pictures:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Kuala_Lumpur
      - UPLOAD_LOCATION=/home/admin/Pictures
      - DB_DATA_LOCATION=/etc/immich/db
      - DB_DATABASE_NAME=immich
      - DB_USERNAME="postgres"
      - DB_PASSPORT="postgres"
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:latest
    volumes:
      - /etc/immich/cache:/cache
    environments:
      - UPLOAD_LOCATION=/home/admin/Pictures
      - DB_DATA_LOCATION=/etc/immich/db
      - DB_DATABASE_NAME=immich
      - DB_USERNAME="postgres"
      - DB_PASSPORT="postgres"
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:42cba146593a5ea9a622002c1b7cba5da7be248650cbb64ecb9c6c33d29794b1
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      - POSTGRES_PASSWORD: "postgres"
      - POSTGRES_USER: "postgres"
      - POSTGRES_DB: "immich"
      - POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - /etc/immich/db:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres -c shared_preload_libraries=vectors.so -c 'search_path="$$user", public, vectors' -c logging_collector=on -c max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on
    restart: always
